### ISSUE TITLE
Should skos:prefLabels of controlled vocabularies be required?

### ISSUE THREAD

**Issue by jakubklimek** [EmidioStani/dcat-ap_validator#9]
In DCAT-AP we are required to reuse EU controlled vocabularies and their items such as http://publications.europa.eu/resource/authority/data-theme/SOCI. It is therefore questionable whether skos:prefLabel should be required as it should be obtained by dereferencing the URI or downloading the vocabulary instead of replicating the labels in the catalog data.

**Comment by EmidioStani** [comment]
Hello Jakub,

I have based the validator on the guidelines where a Category has as mandatory property the skos:prefLabel, also since it is mandatory it is considered an error.

http://data.opendatasupport.eu:3030/sparql-doc/rule-169.html

I do believe this issue should be raised in DCAT-AP working group by saying that it should be an optional property:
https://joinup.ec.europa.eu/community/semic/og_page/dcat-ap
